---
- name: COMMON | Enable backports repo
  apt_repository:
    repo: "deb http://deb.debian.org/debian {{ vagrant_dev_os_version_codename }}-backports main"
    filename: "{{ vagrant_dev_os_version_codename }}-backports"
    state: present

- name: COMMON | Create development group
  group:
    name: "{{ _vagrant_dev_group }}"
    gid: "{{ vagrant_dev_groupid }}"
    state: present

- name: COMMON | Ensure additional groups exist
  when: (vagrant_dev_group_additional | length > 0)
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ vagrant_dev_group_additional }}"

- name: COMMON | Create development user
  user:
    name: "{{ vagrant_dev_username }}"
    comment: "development user"
    uid: "{{ vagrant_dev_userid }}"
    shell: "{{ vagrant_dev_shell }}"
    group: "{{ _vagrant_dev_group }}"
    groups: "{{ vagrant_dev_user_groups_always + vagrant_dev_group_additional }}"
    home: "{{ vagrant_dev_home_dir }}"

- name: COMMON | Set authorized key
  authorized_key:
    user: "{{ vagrant_dev_username }}"
    state: present
    key: "{{ lookup('file', vagrant_dev_public_key) }}"

- name: COMMON | Install development environment packages
  apt:
    name: "{{ vagrant_dev_packages }}"
    state: present
    autoclean: true
    update_cache: true

- name: COMMON | Copy root .bashrc
  template:
    src: .bashrc.root.j2
    dest: "/root/.bashrc"
    owner: "root"
    group: "root"
    mode: 0644

- name: COMMON | Copy user dot files
  template:
    src: "{{ item.src }}"
    dest: "{{ vagrant_dev_home_dir }}/{{ item.dest }}"
    owner: "{{ vagrant_dev_username }}"
    group: "{{ _vagrant_dev_group }}"
    mode: 0644
  with_items:
    - src: .bash_profile.j2
      dest: .bash_profile
    - src: .bashrc.user.j2
      dest: .bashrc

- name: COMMON | Override motd
  when: vagrant_dev_motd_override_enabled
  copy:
    src: "{{ vagrant_dev_motd_override_file }}"
    dest: /etc/motd
    mode: 0644
