---
- name: COMMON | Enable backports repo
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    filename: stretch-backports
    state: present

- name: COMMON | Create development group
  group:
    name: "{{ vagrant_dev_username }}"
    gid: "{{ vagrant_dev_groupid }}"
    state: present

- name: COMMON | Create development user
  user:
    name: "{{ vagrant_dev_username }}"
    comment: "development user"
    uid: "{{ vagrant_dev_userid }}"
    shell: "{{ vagrant_dev_shell }}"
    groups: "{{ vagrant_dev_username }},hitotito-dev,sudo,staff"
    home: "{{ vagrant_dev_homedir }}"

- name: COMMON | Set authorized key
  authorized_key:
    user: "{{ vagrant_dev_username }}"
    state: present
    key: "{{ lookup('file', vagrant_dev_public_key) }}"

- name: COMMON | Install development environment packages
  apt:
    name: "{{ vagrant_dev_packages }}"
    state: latest
    update_cache: true

- name: COMMON | Copy root .bashrc
  template:
    src: .bashrc.root.j2
    dest: "/root/.bashrc"
    owner: "root"
    group: "root"
    mode: 0644

- name: COMMON | Copy user dot files
  template:
    src: "{{ item.src }}"
    dest: "{{ vagrant_dev_homedir }}/{{ item.dest }}"
    owner: "{{ vagrant_dev_username }}"
    group: "{{ vagrant_dev_group }}"
    mode: 0644
  with_items:
    - src: .bash_profile.j2
      dest: .bash_profile
    - src: .bashrc.user.j2
      dest: .bashrc

- name: COMMON | Override motd
  when: vagrant_dev_motd_override_enabled
  copy:
    src: motd
    dest: /etc/motd
    mode: 0644
