---
- name: CUSTOMIZE | 
  become: true
  apt:
    name: "{{ vagrant_dev_extra_packages }}"
    state: present
    autoclean: true
    update_cache: true


#TODO - This should be expanded or removed
- name: CUSTOMIZE | Customize personal settings
  become: true
  become_user: "{{ vagrant_dev_username }}"
  block:
    - name: CUSTOMIZE | Create workspace symlink
      when: vagrant_dev_workspace_shortcut
      file:
        src: "/mnt/workspace"
        dest: "{{ vagrant_dev_homedir }}/workspace"
        state: link

    - name: CUSTOMIZE | Install powerline
      when:
        - vagrant_dev_powerline_status
        - not vagrant_dev_user_powerline_info.installed
      block:
        - name: CUSTOMIZE | Install required packages
          pip:
            name:
              # somehow pip repository does not recognize these packages sometimes
              # - powerline-status
              # - powerline-gitstatus
              - git+git://github.com/powerline/powerline
              - git+https://github.com/jaspernbrouwer/powerline-gitstatus.git
            extra_args: --user

        - name: CUSTOMIZE | Copy powerline configuration files
          copy:
            src: "powerline/"
            dest: "{{ vagrant_dev_homedir }}/.local/lib/python2.7/site-packages/powerline/config_files"
            mode: 0644
            directory_mode: 0755

    - name: CUSTOMIZE | Enable personalized bashrc
      when: vagrant_dev_personal_bashrc_enabled
      copy:
        src: "{{ vagrant_dev_personal_bashrc_path }}"
        dest: "{{ vagrant_dev_homedir }}/.bashrc_personal"
        mode: 0644

    - name: CUSTOMIZE | Enable personalized tmux
      when: vagrant_dev_personal_tmux_enabled
      copy:
        src: "{{ vagrant_dev_personal_tmuxconf_path }}"
        dest: "{{ vagrant_dev_homedir }}/.tmux.conf"
        mode: 0644

    - name: CUSTOMIZE | Enable personalized vim
      when: vagrant_dev_personal_vim_enabled
      block:
        - name: CUSTOMIZE | Install vim-nox for python support
          when: vagrant_dev_personal_vim_enabled
          become: tru
          become_user: root
          apt:
            name: vim-nox
            state: present

        - name: CUSTOMIZE | Copy .vimrc file
          copy:
            src: "{{ vagrant_dev_personal_vimrc_path }}"
            dest: "{{ vagrant_dev_homedir }}/.vimrc"
            mode: 0644

        - name: CUSTOMIZE | Create .vim directory symlink
          file:
            src: "{{ vagrant_dev_personal_vim_remote_dir }}"
            dest: "{{ vagrant_dev_homedir }}/.vim"
            state: link
            force: yes
